In [2]:
# Import libraries and env
import os
import requests
import pandas as pd
from dotenv import load_dotenv
import alpaca_trade_api as tradeapi

%matplotlib inline
load_dotenv()

True

In [3]:
# Alpaca keys & APIs
alpaca_API = os.getenv("alpaca_API")
alpaca_secret_key = os.getenv("alpaca_secret_key")

In [4]:
api = tradeapi.REST(
    alpaca_API,
    alpaca_secret_key,
    api_version="v2")

# Get daily price data for GME over the last 100 days.
barset = api.get_barset('GME', 'day')
start = pd.Timestamp("2021-01-01", tz="America/New_York").isoformat()
end = pd.Timestamp("2021-05-26", tz="America/New_York").isoformat()
tickers = ["GME", "AMC", "SPY"]
timeframe = "1D"

# Get current closing prices for GME, AMC and SPY
df_meme_stonks = api.get_barset(
    tickers,
    timeframe,
    start = start,
    end = end
).df

# Display sample data
df_meme_stonks

##gme_bars = barset['GME']

# See how much GME moved in that timeframe.
#week_open = gme_bars[0].o
#week_close = gme_bars[-1].c
#percent_change = (week_close - week_open) / week_open * 100
#print('GME moved {}% over the last 100 days'.format(percent_change))

                             AMC                                         GME  \
                            open    high     low    close     volume    open
time
2021-01-04 00:00:00-05:00   2.20   2.200   2.000   2.0150   28930595   19.00
2021-01-05 00:00:00-05:00   1.99   2.030   1.910   1.9853   26437127   17.35
2021-01-06 00:00:00-05:00   2.03   2.230   1.970   2.0100   66388766   17.34
2021-01-07 00:00:00-05:00   2.08   2.110   2.020   2.0500   24804044   18.47
2021-01-08 00:00:00-05:00   2.09   2.211   2.070   2.1400   38473534   18.18
...                          ...     ...     ...      ...        ...     ...
2021-05-20 00:00:00-04:00  12.59  12.990  12.030  12.5401   58527226  170.70
2021-05-21 00:00:00-04:00  12.60  12.840  12.050  12.0800   51310401  171.10
2021-05-24 00:00:00-04:00  12.29  13.960  12.170  13.6600  108852667  176.51
2021-05-25 00:00:00-04:00  13.60  16.670  13.552  16.4189  198167188  180.75
2021-05-26 00:00:00-04:00  17.77  19.950  17.260  19.5419  349572000  228.95

                                                                    SPY  \
                               high     low     close    volume    open
time
2021-01-04 00:00:00-05:00   19.1000   17.15   17.2400   9753598  375.31
2021-01-05 00:00:00-05:00   18.0765   17.23   17.3600   4778357  368.10
2021-01-06 00:00:00-05:00   18.9800   17.33   18.3900   5797094  369.71
2021-01-07 00:00:00-05:00   19.4500   18.02   18.1200   5948426  376.10
2021-01-08 00:00:00-05:00   18.3000   17.08   17.6899   6138604  380.59
...                             ...     ...       ...       ...     ...
2021-05-20 00:00:00-04:00  174.9100  166.90  170.4500   2380689  411.80
2021-05-21 00:00:00-04:00  179.2400  170.33  176.7600   3561751  416.87
2021-05-24 00:00:00-04:00  188.4576  173.35  180.0400   4575003  417.34
2021-05-25 00:00:00-04:00  217.1100  181.00  209.3000  14203786  420.33
2021-05-26 00:00:00-04:00  248.4794  225.55  242.4200  19257147  418.87


                              high     low   close    volume
time
2021-01-04 00:00:00-05:00  375.450  364.82  368.85  92938087
2021-01-05 00:00:00-05:00  372.500  368.05  371.32  53668865
2021-01-06 00:00:00-05:00  376.980  369.12  373.53  91989131
2021-01-07 00:00:00-05:00  379.900  375.91  379.06  58862006
2021-01-08 00:00:00-05:00  381.490  377.10  381.24  60275466
...                            ...     ...     ...       ...
2021-05-20 00:00:00-04:00  416.625  411.67  415.24  69408898
2021-05-21 00:00:00-04:00  418.200  414.45  414.95  66355670
2021-05-24 00:00:00-04:00  420.320  417.08  419.12  45510571
2021-05-25 00:00:00-04:00  420.710  417.62  418.25  50976308
2021-05-26 00:00:00-04:00  419.610  417.76  419.04  38369865

[100 rows x 15 columns]

In [5]:
# Create and empty DataFrame for closing prices
df_meme_close = pd.DataFrame()

# Fetch the closing prices of FB and TWTR
df_meme_close["AMC"] = df_meme_stonks["AMC"]["close"]
df_meme_close["GME"] = df_meme_stonks["GME"]["close"]
df_meme_close["SPY"] = df_meme_stonks["SPY"]["close"]

# Drop the time component of the date
df_meme_close.index = df_meme_close.index.date

# Display sample data
df_meme_close

                AMC       GME     SPY
2021-01-04   2.0150   17.2400  368.85
2021-01-05   1.9853   17.3600  371.32
2021-01-06   2.0100   18.3900  373.53
2021-01-07   2.0500   18.1200  379.06
2021-01-08   2.1400   17.6899  381.24
...             ...       ...     ...
2021-05-20  12.5401  170.4500  415.24
2021-05-21  12.0800  176.7600  414.95
2021-05-24  13.6600  180.0400  419.12
2021-05-25  16.4189  209.3000  418.25
2021-05-26  19.5419  242.4200  419.04

[100 rows x 3 columns]

In [6]:
df_meme_close.to_pickle('meme_close.pkl')